### ISSUE TITLE
 Error: Cannot find module './lib/transform' starting from v1.1.4

### ISSUE THREAD

**Issue by tinesoft** [conventional-changelog/conventional-github-releaser#42]
Hi,

Thanks for this great tool!

The last two releases (`v1.1.4` and `v1.1.5`) give me this error (works fine with `v1.1.3`) when running a gulp task:

```
Error: Cannot find module './lib/transform'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<PATH_TO_MY_PROJECT>\node_modules\conventional-github-releaser\index.js:10:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Any idea?

**Comment by hbetts** [comment]
Howdy Tine,

The error you're encountering is entirely my fault. I had not checked the
'files' property of 'package.json', which does not include the 'lib'
folder, so the transform file is not getting published.

This afternoon, when I gave access to a computer, I'll submit a fix to
publish the 'lib' directory.

On May 28, 2017 1:47 PM, "Tine Kondo" <notifications@github.com> wrote:

Hi,

Thanks for this great tool!

The last two releases (v1.1.4 and v1.1.5) give me this error (works fine
with v1.1.3) when running a gulp task:

Error: Cannot find module './lib/transform'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>
(<PATH_TO_MY_PROJECT>\node_modules\conventional-github-releaser\index.js:10:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

Any idea?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/conventional-changelog/conventional-github-releaser/issues/42>,
or mute the thread

**Comment by tinesoft** [comment]
Hi @hbetts,

No problemo,
Keep up the good work!

**Comment by hbetts** [comment]
So I corrected the `files` property of `packages.json` to correctly publish the `lib/` directory.

Using `npm pack` I was able to confirm this fix.

However, during my testing I came across another bug that prevented `conventional-github-releaser` from working correctly. At one point our dependency on the `github` package was upgraded, but not our use of it's API. Then we downgraded that dependency because it broke the package. However, we then accepted a pull request from another person that upgraded the API call (probably fixing the brokenness), but that re-broke our project because of the earlier downgrading of `github`. Therefore I reverted that latter change, so we're now back to the old package _and_ API call.

Version v1.1.7 has been published, and has been confirmed to work on this repository.

Please let us know if you encounter any further problems.

**Comment by tinesoft** [comment]
I can confirm it works great again. 
Thanks for the explanation and the promptness!
